const fs=require('fs'),vm=require('vm'),assert=require('assert');
const data=fs.readFileSync('dist/data.js','utf8'),app=fs.readFileSync('dist/app.js','utf8');let storage={},clock=Date.now(),profile='alice';
function session(){const nodes=new Map(),events={},intervals=[];const node=s=>{if(!nodes.has(s))nodes.set(s,{innerHTML:'',textContent:'',focus(){},scrollIntoView(){},remove(){this.innerHTML=''}});return nodes.get(s)};const context={console,URL,JSON,Date:class extends Date{static now(){return clock}},sessionStorage:{getItem:()=>profile},localStorage:{getItem:k=>storage[k]||null,setItem:(k,v)=>{storage[k]=v}},location:{_hash:'',get hash(){return this._hash},set hash(v){this._hash=v.startsWith('#')?v:'#'+v}},confirm:()=>true,setInterval:fn=>intervals.push(fn),document:{querySelector:node,addEventListener:(n,fn)=>events[n]=fn},window:{scrollTo(){},addEventListener:(n,fn)=>events[n]=fn}};vm.createContext(context);vm.runInContext(data,context);vm.runInContext(fs.readFileSync('dist/profiles.js','utf8'),context);vm.runInContext(app,context);return {context,nodes,events,intervals,run:s=>vm.runInContext(s,context),click:(act,extra={})=>events.click({target:{closest:()=>({dataset:{act,...extra},disabled:false})}})};}let s=session();
assert(s.nodes.get('#app').innerHTML.includes('Learn through examples'));assert.equal(s.run('DATA.tests.length'),10);assert.equal(s.run('DATA.tests.reduce((n,t)=>n+t.questions.length,0)'),650);
s.run('start(5);render()');assert(s.nodes.get('#app').innerHTML.includes('Question 1 of 65'));
s.events.change({target:{id:'',dataset:{answer:'0'},hasAttribute:k=>k==='data-answer'}});assert.equal(s.run('state.attempts[5].answers[getTest(5).questions[0].id][0]'),0);
s.click('explain');assert(s.nodes.get('#app').innerHTML.includes('Every option explained'));assert(s.run('state.attempts[5].seen[getTest(5).questions[0].id]'));
s.click('explain');assert(!s.nodes.get('#app').innerHTML.includes('Every option explained'));assert(s.run('state.attempts[5].seen[getTest(5).questions[0].id]'));
s=session();assert.equal(s.run('Object.values(state.attempts[5].answers)[0][0]'),0);s.run('location.hash="#quiz/5";render()');s.click('next');assert.equal(s.run('state.attempts[5].index'),1);s.click('flag');assert(s.run('state.attempts[5].flags[getTest(5).questions[1].id]'));
assert(s.run('(()=>{const q=getTest(5).questions.find(q=>q.type==="multi");return correct(q,q.correct)&&!correct(q,[q.correct[0]])&&!correct(q,[...q.correct,4])})()'));
for(const type of ['matching','ordering'])assert(s.run(`(()=>{const q=getTest(5).questions.find(q=>q.type==="${type}");return correct(q,q.correct)&&!correct(q,[...q.correct].reverse())})()`));
s.run('getTest(5).questions.forEach(q=>state.attempts[5].answers[q.id]=q.correct.slice());');assert.equal(s.run('score(getTest(5),state.attempts[5]).percent'),100);s.click('finish');s.run('render()');assert(s.nodes.get('#app').innerHTML.includes('100%'));
s.run('state.settings.mode="exam";state.settings.minutes=90;start(6);render()');assert.equal(s.run('elapsed(state.attempts[6])'),5400);clock+=30000;s.run('pause()');assert.equal(s.run('state.attempts[6].remaining'),5370);clock+=60000;s.run('location.hash="#quiz/6";render()');assert.equal(s.run('elapsed(state.attempts[6])'),5370);
s.run('state.attempts[6].remaining=1;state.attempts[6].runningSince=Date.now()');clock+=2000;s.intervals.forEach(fn=>fn());assert(s.run('state.attempts[6].finished'));
s.run('for(const t of DATA.tests){if(!state.attempts[t.id])state.attempts[t.id]={answers:{},seen:{},flags:{},index:0,mode:"study",remaining:7200,runningSince:null,finished:false};for(let i=0;i<65;i++){state.attempts[t.id].index=i;quiz(t.id);explanation(t.questions[i],[],false);}}');for(const route of ['learn','reference','practice','review','sources','topic/transfer','result/5'])s.run(`location.hash=${JSON.stringify('#'+route)};render()`);
console.log('PASS: 650 question views and explanations; answers persist; reveal/hide; flags; exact grading; score totals; reload; timer pause/resume/expiry; all main routes.');

profile='bob';let b=session();assert.equal(b.run('Object.keys(state.attempts).length'),0);profile='alice';let a=session();assert(a.run('Object.keys(state.attempts).length')>0);assert(a.run('state.activity.length')>0);assert.equal(a.run('Object.keys(cleanProfile(JSON.parse(JSON.stringify(state))).attempts).length'),a.run('Object.keys(state.attempts).length'));console.log('PASS: username separation, resume, activity and backup validation');
